### ISSUE TITLE
Order of arguments / Keyword arguments

### ISSUE THREAD

**Issue by cortner** [ranjanan/AMG.jl#30]
Hi - thank you for developing this, I'll be very happy to finally retire  `PyAMG.jl`. 

One question: the order of arguments currently is 
```
solve(ml, b, maxiter, cycle, tol; verbose = false, log = false)
```
I think most users would really prefer to call this with 
```
solve(ml, b; maxiter=..., cycle=..., tol=..., verbose = false, log = false)
```
but if you prefer to keep non-kw-args, then putting `tol` in front seems the more natural option.

**Comment by ranjanan** [comment]
Hi @cortner , thank you for your encouragement. Indeed, I need to clean up the API. I think having them all as keyword arguments would be most convenient to the user. I shall clean this up in a PR.

**Comment by ranjanan** [comment]
I close to make `cycle` a default argument because I dispatch on it.

**Comment by cortner** [comment]
You could just use a barrier

**Comment by ranjanan** [comment]
There is a function barrier internally here: https://github.com/ranjanan/AMG.jl/blob/master/src/multilevel.jl#L105. But unfortunately I still see a performance cost. :-(

**Comment by cortner** [comment]
that’s strange. If you are in principle happy to get pull-requests, then I can play a bit with the user-interface? (no need to accept them of course)

On 8 Mar 2018, 07:58 +0000, Ranjan Anantharaman <notifications@github.com>, wrote:

There is a function barrier internally here: https://github.com/ranjanan/AMG.jl/blob/master/src/multilevel.jl#L105. But unfortunately I still see a performance cost. :-(

**Comment by ranjanan** [comment]
Yes, I'm very open to PRs. I'd love to see what you have in mind.
